create table category (categoryid bigint generated by default as identity, type varchar(255), primary key (categoryid))
create table item (itemid bigint generated by default as identity, description varchar(255), price double, status varchar(255), title varchar(255), zipcode integer, categoryid bigint, userid bigint, primary key (itemid))
create table user (userid bigint generated by default as identity, email varchar(50), firstname varchar(30), lastname varchar(30), password varchar(255) not null, role varchar(255) not null, username varchar(255) not null, primary key (userid))
alter table user add constraint UK_sb8bbouer5wak8vyiiy4pf2bx unique (username)
alter table item add constraint FKrr3uj06scs7dswxs7vtv5gyso foreign key (categoryid) references category
alter table item add constraint FKnhr2sfmswb0vcj96as81hn5fm foreign key (userid) references user
